### ISSUE TITLE
Block installation when not enough memory is available

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#196]
An user reported that he could keep running app installation while not having sufficient memory to run them. The result is that all installation failed without explanation.

**Comment by jsilvestre** [comment]
Is it still the case? I've found code about that in the installation / update code.

**Comment by poupotte** [comment]
Installation is now well blocked if cozy hasn't enough memory. For me, we can close this issue. @frankrousseau , what do you think ?

**Comment by frankrousseau** [comment]
Thank you @poupotte
