### ISSUE TITLE
Can't install apps which aren't in the registry

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#252]
STR
===

- Go to https://demo.cozycloud.cc/#applications
- Copy `https://github.com/cozy/cozy-template.git` in the `install your own application` text field.
- Click install

Expected
===

App gets installed and usable.

Observed
===

App can't be installed. JS console shows `TypeError: app is undefined`

This looks pretty important. @frankrousseau , got any idea?

**Comment by jsilvestre** [comment]
I I haven't been able to reproduce this bug, with 1.0.34 (latest). Can you please update, and try again? Thanks!

**Comment by frankrousseau** [comment]
I commited a fix yesterday. Maybe that's why you can't reproduce it.

**Comment by jsilvestre** [comment]
Actually the problem @bnjbvr has is that app without description in their manifest can't be installed. I'm going to make a fit to detect it.
