### ISSUE TITLE
Updating an app doesn't increment the version number in "Manage your apps"

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#253]
STR
=

- (an app needs to get updated)
- click on "update" next to the app name in "Manage your apps"
- wait until the update is done

Expected
==

The version number of the app gets incremented.

Observed
==

It doesn't get incremented (one needs to reload the page for this).

Example
==

I saw today that I've received an update for files, which was in version `1.0.0`, so I've clicked on update, and once the app returns to the "started" state, the version is still `1.0.0`. Manually reloading the page shows that the new version of files is actually `1.1.0`.

**Comment by frankrousseau** [comment]
+1 I noticed that bug too.

**Comment by jsilvestre** [comment]
very annoying +1
