### ISSUE TITLE
Notifications of updates should dissapear once updates are completed

### ISSUE THREAD

**Issue by Beast141** [cozy/cozy-home#259]
I think that it would be more efficient and useful if the update notifications dissapeared automatically once those updates were finished. Instead of the user manually dismissing them making him/her think that an update was not successful.

**Comment by frankrousseau** [comment]
I noticed two other problems:

* Stack app versions are not properly updated. 
* The platform restart is confusing. A message explaining what's happening would make things smoother.

**Comment by jsilvestre** [comment]
I bump this issue, now the update process is smoother, it's even more disturbing.

**Comment by clochix** [comment]
I think this has been fixed for a while. @Beast141, @frankrousseau could we close this one ?

**Comment by poupotte** [comment]
This issue was fixed. I close it, @frankrousseau if you have still problems, don't hesistae to reopen this issue.
