### ISSUE TITLE
Sprite market icons

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#268]
The market loads an image for each applications. Those images should be in a sprite.
Be careful, there is a mix of SVG and PNG icons.

Please note that the individual icons are still needed during the installation process, if the app's icon cannot be found, it tries to fallback to the one the Home has.

**Comment by frankrousseau** [comment]
What is a sprite?

**Comment by jsilvestre** [comment]
It's a big image with all images inside. You then use the css property `background-position` to display the image you want. It's a technique to reduce the number of HTTP requests when you ave many images to display.

**Comment by Tonours** [comment]
Hi, 
i'm working on a svg sprite for all icons of the application. 
With this technic we can reduce https requests and at the same time increase quality of icons for high density pixel screens. 
I also working on a documentation to increase icons management (icon name + link to iconmonstr).
I don't know what browsers supports is but using SVG forces us to focus on IE9+, is that allright for you ? 
There is no specifics docs about browser support and i'll be curious to know it if there is one.

**Comment by frankrousseau** [comment]
Yes, it sounds good. SVG is already ready for high density pixel screens. The biggest improvement is that il will lead to less requests. Hence, the Home will be faster to load.

**Comment by Tonours** [comment]
Great, apps icons are already in SVG, so it will be really quick to make the sprite.
For all other icons there is a mix between PNG and SVG, i've begin to get SVG from iconmonstr to replace PNG.
Another question is there a front end guidelines for stylesheets, (classes name, modules name etc... by example: https://github.com/lunaweb/style-guide-css ) ?

**Comment by aenario** [comment]
There is : https://github.com/cozy/cozy-guidelines#css--stylus

**Comment by Tonours** [comment]
Cool, thanks for the link

**Comment by m4dz** [comment]
Hi @Tonours!

Good news if you can handle this issue :smile:. For SVG sprite, I suggest we embed the sprite in a _def_ file like in this (unfortunately dead) commit: https://github.com/m4dz/cozy-files/commit/26d8c42afe05ea358096fa6074afb975332b43cb.

For the rest of icons, we use Font Awesome ones as the font icon is embed in our global fonts file declaration (see https://github.com/cozy/cozy-guidelines/pull/17).

Thanks for all the fish!

**Comment by frankrousseau** [comment]
It will be fixed with the new version. Thank you for reporting.
