### ISSUE TITLE
Something is wrong with icons

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-home#279]

**Comment by frankrousseau** [comment]
Could you add more details?

**Comment by aenario** [comment]
During installation of an app from outside the marketplace (the pfm version Ben worked on), it sometimes had the icon, sometimes not. I saw this mornin a PR from @poupotte about this, so it might be fixed.

**Comment by frankrousseau** [comment]
Ok thank you.

**Comment by clochix** [comment]
@aenario could you test once @poupotte's PR has been merged ?

**Comment by clochix** [comment]
Ping @aenario: @poupotte fixed this, could you test ? Thank you !

**Comment by aenario** [comment]
ok for me

**Comment by poupotte** [comment]
Thanks, this issue seems ok.
