### ISSUE TITLE
Navigating in home

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#281]
When browsing an app within the Home, if you click "back" to go the previous page, the URL changed but not the content.

It's probably a tweak to do in the options when we call `router.navigateTo` or something that exists by design.

**Comment by m4dz** [comment]
I saw it when developping the ISEN app. Maybe we should handle pushState/popState in backbone in a more consistent way. I suggest to keep it inmind when we'll develop the brand-new cozy-home version.

**Comment by aenario** [comment]
Is that before or after merging #277 ?

It should fix it

**Comment by frankrousseau** [comment]
@aenario On my Cozy (up to date) the bug is still present.

**Comment by aenario** [comment]
@m4dz , if you work on it :
basically there is a interaction between
https://github.com/cozy/cozy-home/blob/98fbf7bc6d998b522afdb2dbfd57bc1f9fca564d/client/app/views/main.coffee#L200
https://github.com/cozy/cozy-home/blob/98fbf7bc6d998b522afdb2dbfd57bc1f9fca564d/client/app/views/main.coffee#L220-L223

The router.navigate should not be called if the change comes from line 200. Or may be it should be called with a replace: true (not sure if it matters with hashbang urls)

**Comment by m4dz** [comment]
@aenario ok, thanks :smile:

**Comment by poupotte** [comment]
This issue should be fixed. @frankrousseau , can we close it ?

**Comment by frankrousseau** [comment]
This one is fixed but the navigation problem is still present. Let's close that one. We'll reopen it when users will complain about history navigation.
