### ISSUE TITLE
Flash plugin required ?

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#283]
Whenever i login on my cozy, I can see the flash plugin being requested. I've disabled it, and everything seems to work. Is it really needed on every part of all cozy app ?

**Comment by frankrousseau** [comment]
Yes, this is due to an outdated version of socket.io on which Cozy is based on. It's already listed in our todo-list.

**Comment by frankrousseau** [comment]
It should be fixed soon. The code is updated, we just have to publish it.
