### ISSUE TITLE
Improve the quick tour steps

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-home#285]
As we [debates](https://github.com/cozy/cozy-home/issues/267#issuecomment-73225115) in #267, the first implementation of the Quick Tour steps isn't totally acceptable as it for users. Use this issue to reference some solutions and sketchs to find a better way to do it.

**Comment by frankrousseau** [comment]
Yep and let's wait for students feedback. By the way, let me know when #267 is merged. So I can update their Cozy. It will be useful for their research.

**Comment by frankrousseau** [comment]
We will rework it later depending on feedback about the new Home.
