### ISSUE TITLE
Updating the stack often leads to weird behaviour

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#288]
When a user updates the stack, he is redirected to the login screen. But sometimes, after he logs in, the proxy somehow restarts, resulting in the user believing nothing is working, while he just actually gets 401 on each requests.

**Comment by clochix** [comment]
@goofy-bz we opened this issue about the problems you encountered when updating your instance. Please don't hesitate to give @poupotte further explanations.

**Comment by jsilvestre** [comment]
https://github.com/cozy/cozy-controller/commit/6a691c41d7dcfd0c73691694831f790d8f40d6ef should fix this problem.

**Comment by clochix** [comment]
This bug is hard to reproduce, so I think we can trust you and close the issue for now. @goofy-bz please don't hesitate to re-open it if you encounter the problem again.
