### ISSUE TITLE
On a mobile, text under icons on home page are truncated

### ISSUE THREAD

**Issue by scesbron** [cozy/cozy-home#289]
On the home page the text under the icons is truncated on my firefoxos zte open c.

You can reproduce it on firefox if you use the mobile view (Ctrl+Alt+M) and choose a 320x480 resolution.

**Comment by frankrousseau** [comment]
Thank you @scesbron for you bug report. We'll take care of it.

**Comment by frankrousseau** [comment]
@scesbron If you update your Home moduel, things should be fixed. Is it ok for you?

**Comment by clochix** [comment]
Hello @scesbron, have you tried to update your Cozy stack ?

**Comment by frankrousseau** [comment]
We don't have answers since 13 days. We can close this issue. @scesbron if you still meet problems. Feel free to reopen it.

**Comment by scesbron** [comment]
Sorry for not responding sooner. Just tried and it's ok on my ffos phone

**Comment by frankrousseau** [comment]
Great! Thank you for the feedback!
