### ISSUE TITLE
Wrong display on market in small screens

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-home#295]
On small viewports (specially in portrait mode), Market have a bad display when it renders its icons:
![Market on iOS8 - portrait mode](https://cloud.githubusercontent.com/assets/471486/6186281/a899c76c-b377-11e4-95d2-730d8b0df92e.png)

We can:
- improve icons by ensuring they are a constrained square and the corners are rounded to 50% each
- improve grid layout inside each card to prevent text overriding

**Comment by frankrousseau** [comment]
It's fixed by my last pull request. That PR requires a build.

**Comment by m4dz** [comment]
Ok, nevermind, I forgot the build :). Thanks!
