### ISSUE TITLE
Ügly onboarding modal font

### ISSUE THREAD

**Issue by Kloadut** [cozy/cozy-home#296]
I use a typical ugly serif font by default on my OS in order to quickly spot those things.
Yes I am evil.

![capture du 2015-02-18 16 14 39](https://cloud.githubusercontent.com/assets/1279740/6249851/5721bbe4-b78a-11e4-8f8f-b3eed0325625.png)

(Also note the french mistranslation "Bienvenue sur" and "Bienvenue dans", and the notification icon a bit too close to the bottom of the menu bar)

**Comment by frankrousseau** [comment]
Yes we have the same problem in the Files app in tag input and share modal.
