### ISSUE TITLE
"Install from git" field is barely readable

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-home#299]
The font is very thin and orange over white.
We usually c/p something in it, so no big deal, but i hurt my eyes every time i type there.

**Comment by jsilvestre** [comment]
Can you please provide a screenshot? It seems to be ok for me.

**Comment by frankrousseau** [comment]
Did you try the latest verion of home. Now fonts are really bigger.

**Comment by aenario** [comment]
oh yes, my bad !
