### ISSUE TITLE
update of apps and platform

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-home#301]
When you have the modal after you clicked on the update of an app, you still can clic on the plateform update. Some other combinaison of updates are possilbe because people are likely to quickly press on both "update plateform" and "update all apps" (or just one app).
If not done, the Home should :
  * after the launch of a plateform update : freeze the buttons of updates of apps (each app and the "update all" button)
  * the update of the plateform should wait for the end of the installation or update of apps.
  * limit what can be clicked / focused (tab), when on a modal

**Comment by poupotte** [comment]
This issue is fixed in new home version (2.1.11)
