### ISSUE TITLE
Disk space left is not correct

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#304]
As reported on the forum by sak, the disk space can go crazy sometimes: https://forum.cozy.io/t/petit-bug-occupation-disque/273

**Comment by frankrousseau** [comment]
It's related to diskspace units. When Tera is involved, it leads to a wrong display of available space.

**Comment by Peltoche** [comment]
If you change the path, that not follow, he keep, the old size.

**Comment by poupotte** [comment]
Hi @Peltoche , 
I'm not sure to understand. 
You have an uncorrect size if you change your couchdb location ? 

If it's the case, your problem is similar to #380. It should be fixed in the new controller version.

**Comment by clochix** [comment]
@Peltoche I think this has been fixed with the latest controller version (published early this week) and in the development branch of the Home. Would you like to try to test now, or wait until we release the Home to the stable branch ?

**Comment by Peltoche** [comment]
Yes, I moved on controller 2.0.26 and it's fixed! Thanks a lot!
Now I have this -> 351 / 3.9 T

Juste some another comments:
- Maybe that will be great to add the "size type" on the used space? Like 351M/3.9T.
- That's print 3.9T and it's my total size but I use some of this space in other applications or data so in reality I haven't 3.9T but 2.XT of space not used. So you print total space but not free space and that would be a big différence...

**Comment by clochix** [comment]
\o/ Thanks you for testing @Peltoche and congrats to @poupotte for fixing.

@poupotte could you add the unit of the used space ?

Regarding your second comment, what do you suggest we could do to improve this ?

**Comment by clochix** [comment]
@aenario could you just add the unit on the used space ?

**Comment by clochix** [comment]
Hi @Peltoche,
The unit of the free disk space has hust been added, so I think this ticket is over ☺ Thanks everybody !
