### ISSUE TITLE
"install your app" input 

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-home#307]
When you are in the market place, wherever the focus is, when you press any key, you leave the market place to go on the home.
This is especially a problem when you need to paste an URL in the "install your app" input text.
ps : this bug has been seen and can be repeated in "ben-test" vm, but it's ok on 2 other vm... strange.

**Comment by poupotte** [comment]
mmm... strange, I don't arrive to reproduce your issue on your vm "ben-test" (firefox and chrome).

**Comment by poupotte** [comment]
@Benibur can't reproduce this issue. @frankrousseau , I propose to close this issue. If someone else has this bug, we'll reopen it.
