### ISSUE TITLE
Impossible to erase all notifications when there are too many of them

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#310]
STR
===

- Get ~30 notifications on your cozy.

Expected
===

One can close them all with the "dismiss all" button.

Observed
===

The "dismiss all" button is too low to be displayed and thus to be clicked...

**Comment by frankrousseau** [comment]
Thank you @bnjbvr for reporting. I noticed it too.

**Comment by poupotte** [comment]
The new home version (from 2.0.0) fixes this issue.
