### ISSUE TITLE
can't login, cozy seems lost

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#313]
I can't get my cozy to work again.
When entering login info, nothing happens (the blue button does not even have any text inside). Sometimes after some refresh, I'm being shown the home page, but it's nearly empty (no app on the "desktop", only not-working icons on the right).

:'(

**Comment by frankrousseau** [comment]
It looks like your data-system is down. I'm going to give a look.

**Comment by frankrousseau** [comment]
I restarted your Cozy. Does it work now?

**Comment by dkm** [comment]
no :( still the same behavior (login silently fails, sometimes redirected to faulty home page...)

**Comment by dkm** [comment]
it looks like it works again... possible browser bug ?

**Comment by jsilvestre** [comment]
It is a known bug of Cozy: when you log out (or that you forced out, i.e. Cozy restarts), Home does not detect and inform the user that he must refresh the page / or event better, refresh the page itself.

**Comment by dkm** [comment]
Ok, but I've tried to refresh, force refresh, retype the URL... I don't know if it's related or not, but when I closed the tab and retried in a new one, it worked.

I also had this kind of problem within the photo app, I will add a new issue (sorry)

**Comment by frankrousseau** [comment]
Ok let's close this issue.
