### ISSUE TITLE
Icon and text mismatches between apps

### ISSUE THREAD

**Issue by jankeromnes** [cozy/cozy-home#314]
During the installation of Konnectors, the app name text is at the wrong height:

![cozy-text-height-problem](https://cloud.githubusercontent.com/assets/599268/6546502/db6df03c-c5b5-11e4-81a8-05bf7ddf6b6f.png)

Then, the Konnectors icon is way bigger than Kresus':

![cozy-icon-size-problem](https://cloud.githubusercontent.com/assets/599268/6546503/df66329e-c5b5-11e4-81b3-74d3cb51f38a.png)

**Comment by m4dz** [comment]
Thanks for viewing it! We'll revamp/redesign home and proxy soon (I hope), so I think we can fix it at this time :).

**Comment by frankrousseau** [comment]
It will be fixed with the new version. Thank you for reporting.
