### ISSUE TITLE
Force TLS

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#315]
Not sure if it's the correct repository for this issue.

At this point, we can log into a cozy in two different schemes: http or https. It would be nice that the http page just redirect the user to the https page, so that we ensure communications between the browser and the server are encrypted.

While a workaround would be to use JS redirection (window.location), the better way would probably be to handle this at the lowest level, that is, nginx/apache when that's possible, or the cozy-home / cozy-proxy non-SSL server should redirect (301) to the correct same page, but with a different scheme.

**Comment by bnjbvr** [comment]
Romain pointed me to https://github.com/cozy/cozy-setup/pull/135, which solves the issue for newer systems (installed after this PR), so the nginx/apache part is already done, yay!

**Comment by frankrousseau** [comment]
Unfortunately, the fix doesn't work. There is till work required.

**Comment by frankrousseau** [comment]
It was finally fixed (in Ubuntu, default files were still active).
