### ISSUE TITLE
Closing the first-run-experience is weird

### ISSUE THREAD

**Issue by jankeromnes** [cozy/cozy-home#323]
When opening the Home app in my Cozy, I see a first-run-experience wizard trying to suggest apps.
- There is no "x" button to close it.
- However, when I press "Ctrl", it closes, which is weird.

**Comment by frankrousseau** [comment]
You're right. I noticed same kind of problems. Thank you @jankeromnes for reporting!

**Comment by clochix** [comment]
the first run wizard is being refactored, so this issue is not relevant anymore. Thanks for reporting @jankeromnes ☺
