### ISSUE TITLE
Impossible to install new apps using Git URLs

### ISSUE THREAD

**Issue by jankeromnes** [cozy/cozy-home#324]
Steps to reproduce:

1. Start your latest `Cozy Home` app.
2. Go to `Choose your apps`.
3. Try to install [Kresus](https://github.com/bnjbvr/kresus) by typing `https://github.com/bnjbvr/kresus` into `Install your own applications` at the bottom.

Expected:

- You can type the address and install Kresus.

Actual:

- As soon as you've typed a few letters, `Cozy Home` goes back to the `Access to your apps` screen.

**Comment by frankrousseau** [comment]
It looks fixed. @jankeromnes could you update your home and try again?

**Comment by jankeromnes** [comment]
@frankrousseau It doesn't look fixed for me.

The way I test it, on Ubuntu 14.04, with Docker 1.2.0 and latest Firefox Developer Edition:

    # Install Cozy using Docker
    git clone https://github.com/cozy-labs/cozy-docker
    cd cozy-docker
    sudo docker build . -t cozy
    sudo docker run -d -p 80:80 -p 443:443 cozy

Then, I open `https://localhost` in my latest Firefox Developer Edition, and:

1. Complete the registration with `bla@bla.bla` and password `blabla`
2. Go to `Choose your apps`, and scroll to the bottom
3. In `Install your own application`, try to type in `https://github.com/bnjbvr/kresus`

Then the bug happens. I don't think it's related to Docker, but I gave you all the info just in case.

**Comment by jankeromnes** [comment]
Actually, when I actually go through the setup wizard, and install all the apps, the problem goes away. Maybe it only happens when the wizard wasn't completed / there aren't any apps?

**Comment by m4dz** [comment]
Hi @jankeromnes,

it was related to the wizard but was fixed in the last home release (see 6498f20). Maybe the home version embeded in the docker image isn't up-to-date (poke @Kloadut)?

**Comment by jankeromnes** [comment]
I'm not able to try to reproduce, because when I build and run `cozy-docker`, I'm now unable to access the web app (connecting to `https://localhost` yields `ERR_CONNECTION_CLOSED`).

**Comment by jankeromnes** [comment]
All good now! It seems Cozy just took a very long time to initialize itself. I tried and couldn't reproduce this bug anymore. Thanks!
