### ISSUE TITLE
Use an alternative method to get free memory

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#325]
A user is trying to install Cozy on FreeBSD. The installation worked fine, but he is unable to install applications.
To check if the instance has enough free memory, we use the OS `free` utility, which is not available on FreeBSD.
We should check if `free` is available and, otherwise, fallback to `os.freemem()` (less accurate, but better than nothing).

**Comment by clochix** [comment]
The user reported that my patch did the job, should I make a PR ?

**Comment by frankrousseau** [comment]
Yes I thought it was already merged.
