### ISSUE TITLE
In the installed apps list, show from which branch is based an application

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#336]
I often install applications from the app command line which are based on a github branch which isn't master. I'd like to see the name of the branch in the list of installed applications, next to the github URL, for instance.

It could be shown either all the time, or only when the branch isn't `master`.

**Comment by frankrousseau** [comment]
Good idea, thank you  @bnjbvr !

**Comment by clochix** [comment]
Thanks, that's really useful and works like a charm.
