### ISSUE TITLE
RAM free problem on ubuntu 15.10

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-home#339]
With a fresh Cozy installation on ubuntu 15.10 a user have a bad free memory value.

RAM 3920/3920 but he have 3Gb free.

Discussion in french in our forum:
https://forum.cozy.io/t/ram-pleine/548

**Comment by ajeantet** [comment]
Hi,
I have the same bug on ubuntu 15.04 fresh install
Free returns
<quote]>
             total       used       free     shared    buffers     cached
Mem:       4020944    1794464    2226480      16232     100584    1121592
-/+ mémoire tampon/cache :     572288    3448656
Mémoire d'échange :     523260          0     523260
</quote>

**Comment by clochix** [comment]
Hi @ajeantet,
some fixes have been published. Could you try to update to the latest version of Home application, and see if free RAM displayed is more accurate ? Thanks !

**Comment by clochix** [comment]
I will close this one, @ajeantet don't hesitate to re-open it if you encounter again this problem. Thanks a lot for the fix @poupotte !
