### ISSUE TITLE
Do not update version of app when update fails

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#340]
Hello,

sometimes, the update of an app fails (for any reason). The diplayed installed version inside config-applications is the updated one, shouldn't it be the version of the previous one?

**Comment by frankrousseau** [comment]
I think broken app should be removed. This state is useless. This behavior would fix your problem too.

**Comment by frankrousseau** [comment]
Thank you for reporting @ZeHiro

**Comment by poupotte** [comment]
It works well on new home version. Thanks @frankrousseau
