### ISSUE TITLE
Diplay problems and unaccessible "stop application button"

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#341]
In the "config-applications" page, when : 

- when "app name" + "app version" + "status" is quite long (eg : data braser 1.04 démarrée) 
- an app is running  (so that "auto stop" app check box is displayed )
It is almost impossible to stop an app on clicking on the "stop icon" : when the mouse is over the icon, the icon displays "arrêter cette application". The stop icon with "arrêter cette application" + update icon + delete icon become to long for the width of the applist column. So a new line is created with this text. 
Thestop icon is not anymore under the mouse, ans moving the mouse to click on it removes the ""arrêter cette application" text, and the text can now fit one line, the stop icon comes back to its position. 
On the screnshot below, my mouse is just above the "arrêter l'application" button. If I try to click on it, the button is reduced to the "stop" icon, and on line remains.
![bouton](https://cloud.githubusercontent.com/assets/7999082/7370561/3a2e6066-edbb-11e4-9d4d-2560d28ca8ad.png)

Thanks

**Comment by frankrousseau** [comment]
Thank you for reporting. We'll fix it for the next version that will be published in two weeks.

**Comment by frankrousseau** [comment]
It will be fixed in the new version. The publication on the official repository is planned for June, 15th.
