### ISSUE TITLE
Impossible to paste password on account creation

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-home#342]
Not sure if this is the right cozy project to put my issue, feel free to move it. 

I generate by password in a separate software and then paste it into the initial form of the cozy welcome screen. The button to submit the form seems active, I can clic it, but it doesn't do anything. I then see that there is still a message about the password should have so many letters etc... I add a space then remove it from the password and the form detects the password is valid according to the rules. I can then submit the form successfully. 

This is a cozy running inside of a docker. 

I then can't login to my cozy but I think that's a separate bug.

**Comment by frankrousseau** [comment]
Thank you @arthurlutz for reporting we'll take care of it.

**Comment by clochix** [comment]
@frankrousseau do you now if it has been fixed in the new onboarding ?

**Comment by frankrousseau** [comment]
I didn't try. That's a work for @poupotte or @jsilvestre.

**Comment by poupotte** [comment]
This issue seems fixed for me.

**Comment by clochix** [comment]
Thanks @poupotte for checking, let's close this one ☺
