### ISSUE TITLE
Password on login screen not remembered by browser (firefox)

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-home#345]
The login form for cozy does not suggest the browser to remember the password. It would be nice if it did.

**Comment by frankrousseau** [comment]
Thank you for reporting. @bnjbvr noticed it too and proposed a PR. That should be fixed soon.

**Comment by frankrousseau** [comment]
It will be fixed in the new version. Thank you again.

**Comment by arthurlutz** [comment]
In which version can we expect this to be delivered ?

**Comment by frankrousseau** [comment]
In version 2.0.0 that will be out on June, 15th.
