### ISSUE TITLE
Applications are moved to the top (behind the top bar)

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#351]
See: https://github.com/cozy/cozy-emails/issues/328

I noticed the behaviour in Tasky too.
I think it might come from: https://github.com/cozy/cozy-home/blob/master/client/app/views/main.coffee#L235

**Comment by frankrousseau** [comment]
It looks related to React. I think it happens when an error is not properly catched.

**Comment by poupotte** [comment]
@jsilvestre , @frankrousseau , this issue is still relevant ?
(Problem is solved for emails)

**Comment by poupotte** [comment]
This issue seems solved. I close this issue. @frankrousseau , @jsilvestre , don't hesitate to reopen it if you have still this issue.
