### ISSUE TITLE
Update platform stuck at confirmation step

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#353]
As a notification was pushing me to update the platform, I simply clicked on "update platform" within the notifcation. I have now to confirm or cancel the order, but the "update" button is not responding. I can click it without any effect.
Cancel works. Notification is still present and the same behavior can be reproduced.

**Comment by frankrousseau** [comment]
@dkm It's due to the fact you are running a special version of the Home. Thank you for notifying. We'll perform the update through the UI.

**Comment by poupotte** [comment]
I can't reproduce this issue. @frankrousseau , can we close this issue if it concerns  only a special version ?

**Comment by frankrousseau** [comment]
Let's close it then. It's probably due to an edge case of `import-google` app.
