### ISSUE TITLE
[new home] Issue when updating the platform

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#354]
STR
===

- go to the settings section ("Etats")
- click on "update" next to the platform version numbers

Expected
===

Updates starts and normally finishes.

Observed
===

Nothing happens, and in the JS console this shows up:
`TypeError: _this.stackApplications is undefined app.js:4620:6`

**Comment by frankrousseau** [comment]
Thank you for reporting.

**Comment by frankrousseau** [comment]
It's related to the fact you use a version based on the development branch. We'll reopen this issue if it still occures once the changes are merged into the master branch.
