### ISSUE TITLE
[new home] Missing translations in the quicktour wizard

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#355]
In particular, steps 3 ("continue to import"), step 4 ('quicktourwizard.import title' + 'quicktourwizard.import content')

**Comment by frankrousseau** [comment]
Thank you for reporting. That will be fixed soon for self hosted users with development branch.

**Comment by frankrousseau** [comment]
It's fixed in the development branch. Thank you for reporting.
