### ISSUE TITLE
[new home] Can update an empty password

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-home#357]
STR
===

- go to settings
- click the "save your new password" button

Expected
===

Either nothing happens, or there's an error stating that I can't leave any of the 3 password fields blank.

Observed
===

`Your new password is set`.

Now I am afraid to log out...

**Comment by frankrousseau** [comment]
Don't worry you can log out :)

**Comment by clochix** [comment]
Thanks @frankrousseau, we now have a message warning that the new password is too short.
