### ISSUE TITLE
Add icons to notification bar buttons

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#369]

**Comment by clochix** [comment]
Without a description nor a link to the commit, it's hard to know what to test.
I noticed:
 - a new bell icon;
 - icons on the bottom button in notification menu;

Do I miss something ?

**Comment by frankrousseau** [comment]
Crappiest ticker ever written. I can't understand what this ticket means. :_(... 

Aha, I remember! It means that icons were missing in the logout and dismiss all buttons.

**Comment by clochix** [comment]
Thanks, so this seems to be done ☺
