### ISSUE TITLE
Being able to see the app logs from the web UI

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#372]

**Comment by clochix** [comment]
\o/ That's definitively very useful.
May I ask you one last think ? Could you remove the non-printable chars used to have color in terminal ?

**Comment by frankrousseau** [comment]
Don't know how to do that. Any idea? A simple replace?

**Comment by clochix** [comment]
`log.replace(/\033\[\d+m?/g, '')` should do the job.

**Comment by frankrousseau** [comment]
Ok, thank you.

**Comment by clochix** [comment]
Thanks, it works well now ☺
