### ISSUE TITLE
Reboot of instance is broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#378]
When I click on the button to reboot the instance, I have the following error message in browser console:
```
TypeError: this.stackApplications is undefined in app.js (line 4876, col 4)
```

Here's the broken code:
```
  ConfigApplicationsView.prototype.onRebootStackClicked = function() {
    this.rebootStackBtn.spin(true);
    this.spanRefresh.show();
    return this.stackApplications.rebootStack(function() {
      return location.reload();
    });
  };
```

@frankrousseau : this is annoying, do you think you'll have time to have a look during this sprint ?

**Comment by frankrousseau** [comment]
Yes it's a big issue. I had it in mind. I thought it was related to the development branch. I was waiting for the merge with master to fix it. But it looks like it's something else.

**Comment by clochix** [comment]
@frankrousseau this doesn't seem to be fixed, do you think you'll have time to have a look at this, or should I ask someone else ?

**Comment by clochix** [comment]
Sorry, it seems to work now, it seems like I had some cache problem. Is it ok from your point of view ?

**Comment by clochix** [comment]
It works fine now, thank you !
