### ISSUE TITLE
Fix hard drive usage calculus

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#380]
The disk space available displayed in the States in-app is wrong. It should look for the database storage location on written in the Couchdb config file.

**Comment by clochix** [comment]
@frankrousseau I'm not sure to understand what did you meant, so could you check if latest fixes from @poupotte displays the value you expected ?

**Comment by frankrousseau** [comment]
It's fixed by my own changes. Let's close this issue.
