### ISSUE TITLE
Allow to set app as favorites

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#381]
With the new home, apps cannot be organized freely. It's annoying because favorite apps require to scroll in the main dashboard to be accessed.

We should allow to "pin" favorites apps so they appear first in the application list located in the main dashboard (home).

**Comment by clochix** [comment]
Thanks @frankrousseau, it works well ☺
Two last points:
 - the alternate text when hovering the star is not translated;
 - shouldn't favorited apps have a yellow star instead of a black one ?

Also, this feature is great, but hard to discover. Any idea on how to make it more discoverable ?

**Comment by frankrousseau** [comment]
I won't be able to work on this until july.

**Comment by clochix** [comment]
Pinging our UX stars for advice on how to make this feature more discoverable /cc @m4dz @kelukelu.

**Comment by kelukelu** [comment]
Last time I suggested Frank to add a button "favorite" in the buttons group (with remove, stop, show logs)

**Comment by clochix** [comment]
IMHO we already have too many actions in this group. It looks like a big block of blue, and few people will take the time to read the label of each button. Maybe should we also think of refactor this menu to make it more attractive.

**Comment by kelukelu** [comment]
I guess you're right

**Comment by poupotte** [comment]
With new design, mark as favorite an application is more visible.
@clochix , Your two remarks of are now fixed. Can I close this issue ?

**Comment by clochix** [comment]
Yes you can!
