### ISSUE TITLE
Sync icon missing (xml error SVG)

### ISSUE THREAD

**Issue by silvyn** [cozy/cozy-home#392]
Hi,

The SYNC app icon is broken. If I've a look at source, there is a xml error in the SVG (cozycloud.cc/api/applications/sync.svg)

Erreur d'analyse XML : préfixe non lié à un espace de noms
Numéro de ligne 2, Colonne 1 :
<svg
^

**Comment by clochix** [comment]
Thanks for reporting @silvyn.
@m4dz ou @kelukelu, could you have a look at this please ?

**Comment by kelukelu** [comment]
It should be fixed with the new home

**Comment by clochix** [comment]
@silvyn did you update to the new home ? Is it fixed now ?

**Comment by clochix** [comment]
@kelukelu other users confirms the icon is still bloken, even after upgrading Home to the latest version, restarting the instance and emptying the cache. Could you investigate. (FTR, on my instance api/applications/sync.svg is in fact a PNG, not a SVG image)

**Comment by kelukelu** [comment]
To fix this issue, you need to remove the Sync app (thanks to the Status app). 
And install it again (thanks to the Store app).
Home Icons are not updated with the newest version of apps or platform. So far to get the last icons you need to uninstall the application and install it again.
We need to figure out a way to fix it from a technical point of view.

**Comment by silvyn** [comment]
@clochix not better with update. Finaly I've delete app. Try to reinstall it, but seems take time..

**Comment by clochix** [comment]
Hello @silvyn,
Did reinstalling the Sync application fix the icon problem ?

**Comment by silvyn** [comment]
Hi @clochix, yes it's ok since reinstall. So I close and comment :)
