### ISSUE TITLE
Close notification panel when clicked on "ouvrir  l'application"

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#396]
When opening a notification on the new home (2.0), and "ouvrir l'application" is clicked,
the notification panel should be closed, as otherwise it is on top of the application, and another click is necessary to completely see the application content.
It should be the same behaviour when the 'effacer toutes les notifications 'button is clicked

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro, we'll do our best to fix this.

@frankrousseau, do you think it would be easy to close the notification panl when a new application is opened ?

**Comment by clochix** [comment]
Thanks @poupotte, it works great now ☺
@ZeHiro the fix will be available in next version of the application, in a few days.

**Comment by clochix** [comment]
The notification panel is closed, but the notification is not removed. I wonder if we shouldn't also remove it when opening the application.

**Comment by ZeHiro** [comment]
OK, i'll test it. To me the notification should be closed.

**Comment by poupotte** [comment]
Notification should be remove with last commit https://github.com/poupotte/cozy-home/commit/af1454a83607be7be1dfb85bb3a19b9f598cb424

**Comment by ZeHiro** [comment]
It is, thanks @poupotte
