### ISSUE TITLE
La page demo Cozy est détectée comme malware

### ISSUE THREAD

**Issue by HLFH** [cozy/cozy-home#403]
Salut mes chers compatriotes,

Attention. La page demo de Cozy est listée (faux-positif bien entendu !! ligne 6425) dans la liste [Malware-domains](http://www.malware-domains.com/) "Just-Domains", aussi liée à l'extension uBlock Origin.

[Vous pouvez les contacter ici.](http://www.malwaredomains.com/?page_id=13)

Je fermerai quand la liste sera corrigée et mise à jour.

Merci d'avance,

**Comment by clochix** [comment]
Merci du signalement @HLFH, nous avons effectivement constaté que le démonstrateur figure sur plusieurs listes de serveurs distribuant des logiciels malveillants.

Un utilisateur a téléversé voici plusieurs semaines quelques fichiers vérolés dans l'application Files du démonstrateur, ce qui a conduit à cette mise sur liste noire.

Nous sommes en train d'étudier les moyens pour éviter que cela se reproduise, et demanderons ensuite à nous faire retirer de ces listes noires.

En attendant, vous pouvez aisément ajouter une exception dans uBlock afin d'utiliser notre démonstrateur.

**Comment by jsilvestre** [comment]
C'est un problème délicat à traiter, je ne sais pas si nous en serons capable, en tout cas rien ne sera fait dans les prochaines semaines sauf changement de contexte notable. Toutes nos excuses pour la gêne occasionnée...

**Comment by clochix** [comment]
Pour information, je viens de récupérer la dernière version de la liste des domaines suspects de ce site, et Cozy ne semble plus y figurer.

@jsilvestre dans un premier temps, nous pourrions ajouter à Files quelques restrictions via des variables globales : tester le type MIME du fichier et refuser les exécutables.

**Comment by HLFH** [comment]
Cozy n'y figure plus effectivement !

**Comment by jsilvestre** [comment]
Excellente nouvelle, je clos donc le ticket. Merci pour votre vigilance @clochix et @HLFH !
