### ISSUE TITLE
Missing french locale for 'refresh page'

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#404]
Hello,
when clicking on 'Mettre à jour'  of the plateforme section of 'Etats' and thes click 'OK' , the only displayed text is :  'refresh page' . The locale is 'FR' on my cozy.
![capture d ecran de 2015-06-18 08-19-04](https://cloud.githubusercontent.com/assets/7999082/8225281/d6b6d982-1592-11e5-8ca1-8ea638901a88.png)

**Comment by clochix** [comment]
Thanks @ZeHiro for reporting, I noticed the same bug yesterday but didn't investigate. We'll have a look at it.

**Comment by clochix** [comment]
It works now, thanks ☺
