### ISSUE TITLE
When update of plateform is done, the notification 'New plateform is available' is done

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#405]
Hi,

This morning, a new version of the plateform was availabe, so a notification was here.
I did the update, but after the update is finished, the notification was still here.

**Comment by clochix** [comment]
Thanks for reporting.
@poupotte, any idea ?

**Comment by poupotte** [comment]
No idea, it seems work on my cozy :/

**Comment by clochix** [comment]
Thank you @poupotte. I didn't reproduce.
@ZeHiro do you still have the notification after login out and in again ?

**Comment by ZeHiro** [comment]
After the update, re-logon, the notification is still here, but it deseappeares a few seconds later, maybe it is just because the notifications are requested later in the process.

**Comment by clochix** [comment]
@ZeHiro did you have the same behavior after latest update of the platform ?

**Comment by ZeHiro** [comment]
No more problem with this one
