### ISSUE TITLE
Duplicate application icons when going back to home from an application (email)

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-home#407]
Cozy Instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.0
Proxy: 2.0.0
Home: 2.0.1
Controller: 2.0.24
emails -  0.9.1

Step to repoduce:
1. Open the email application
2. Do whatever you want in it
3. Click on the Go back Home button

What's happening:
A new icon appears just below the application icon (see below)
![capture du 2015-06-18 10-20-19](https://cloud.githubusercontent.com/assets/1799460/8227114/a485b21e-15a4-11e5-9feb-f1d2d1ec0b9b.png)

What sould happen:
Home should only display application icon

**Comment by clochix** [comment]
Waouh, you have been well educated, this is definitively the way to report a bug ;-) Tanks for reporting. I think this one is related to #400 and #401, we'll have a look.

**Comment by clochix** [comment]
Same as #400 and #401, should be fixed in next release ☺
