### ISSUE TITLE
`submitPassword is not defined` on login page

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#409]
When I submit the login form, I see a javascript error message in Firebug console.

**Comment by poupotte** [comment]
It's an issue which concerns proxy application.
I think @frankrousseau 's commit (https://github.com/cozy/cozy-proxy/commit/510563bf4521b82f527cd42504827620ba7c9649) should fix is

**Comment by clochix** [comment]
I still see this message in the console. @frankrousseau, any idea ?

**Comment by frankrousseau** [comment]
I think it's fixed. Whatever the proxy is fully refactored. Let's close this one. Thx @clochix for reviewing.
