### ISSUE TITLE
Fix delete request for notifications

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#422]
Hello,

On Cozy (self hosted) : 

Data System: 2.0.4
Proxy: 2.0.0
Home: 2.0.2
Controller: 2.0.24

When a "installation fail"notificaiton is raised,
The DELETE http request get a 404 answer. The notifications are kept in the DB and reappear next time the page is updated. The delete request is sent by clicking on the cross of the given notification.

The "DELETE ALL" button works fine.

**Comment by clochix** [comment]
Thanks for noticing, we'll take care of this.

**Comment by clochix** [comment]
I'm unable to reproduce, so I think this is fixed. Thanks ☺

**Comment by ZeHiro** [comment]
I get nice "204" responses, thanks
