### ISSUE TITLE
Starting an app should open it

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#423]
Our beloved user @goofy-bz find it disturbing that, when from the application management page he clicks on the button to start an application, nothing seems to happen.
When a user clicks on Start, he probably expect the application to really start in front of him, not in the background.

**Comment by clochix** [comment]
Thanks a lot @poupotte, @goofy-bz will be happy ^^

**Comment by goofy-bz** [comment]
I confirm this is working as expected!
