### ISSUE TITLE
Don't allow to update instance URL on hosted instances

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#426]
On the demos instances we host, users are allowed to update the url of their server, but this change will have no effect, so I think this field should be read-only.

**Comment by nledez** [comment]
Yes, on all instances we manage. Good idea :+1:

**Comment by neurolit** [comment]
Thanks @nledez ;-)

**Comment by nledez** [comment]
Welcome @neurolit :)

**Comment by nledez** [comment]
May be be also added to Debian package. What do you think about that? cc @clochix @Kloadut

**Comment by clochix** [comment]
\o/ It works, thanks everybody !
