### ISSUE TITLE
Display a changelog on application update

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#441]
As reported by Michaël (nerdherd45.cc.cc) and many other users, not knowing what's new is a little bit frustrating when updating an application. We should find a way to, at least, display the full changelog of the application.
Maybe adding a `CHANGELOG.md` file to each repository. Or a field in `package.json` with the name of the changelog file…

**Comment by nicofrand** [comment]
I think it is a duplicate : https://github.com/cozy/cozy-home/issues/206 ?
That would be a really nice feature to have !

**Comment by frankrousseau** [comment]
It's defintely a duplicate!

**Comment by poupotte** [comment]
I close this issue because it's a duplicate. If you want follow development, see #206.
