### ISSUE TITLE
Support message not sent when logs are too heavy

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#444]
When a user use the contact form in Help screen, we attach the logs of every applications to the message. If log files are too heavy, Postfix refuse to send the message. User has no feedback and doesn't know that it didn't work.

**Comment by clochix** [comment]
Maybe could we gzip the logs to minimize the risk of reaching some limitation (event if we increase the max message size the server can send, some intermediate server may refuse message if it is too big)

**Comment by aenario** [comment]
Or only take the last N bytes of log files (should probably wait for syslog)

**Comment by nledez** [comment]
May be start with compression (tar cz for example) is a good idea.

**Comment by nledez** [comment]
For now I've just update postfix configuration in our infrastructure to allow to send 30Mb messages.

**Comment by clochix** [comment]
I can confirm that it works on production, closing this, thanks a lot awesome @poupotte
