### ISSUE TITLE
Icon still spining after app start

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#451]
Step to reproduce:
 - click photo app icon [icon starts spinning, then goes back to normal icon, then app starts...]
 - when in photo app click 'back to home'

Photo app icon is spinning endlessly.

Maybe related to #400 ....

**Comment by clochix** [comment]
Hello @dkm,
We thought it was fixed in latest version of the home.
Could you give us the versions of the stack applications ? thanks.

**Comment by dkm** [comment]
On 02-07-2015 14:59, Clochix wrote:
> Hello @dkm [1],
>  We thought it was fixed in latest version of the home.
>  Could you give us the versions of the stack applications ? thanks.
> 


Data System: 2.0.5
Proxy: 2.0.1
Home: 2.0.3
Controller: 2.0.27


Note that after few hours, the icon is back to normal...

**Comment by poupotte** [comment]
@dkm , this issue should be fixed now, is it still relevant ?

**Comment by poupotte** [comment]
I close this issue, I can't arrive to reproduce this bug. Don't hesitate to reopen it if necessary

**Comment by dkm** [comment]
Sorry for the lack of answer, I did not see that bug again. Sorry if you can't reproduce it.
