### ISSUE TITLE
Display bug for applications installed from another market

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#460]
When a user uses another market (e.g. ISEN users), 
* during permission acceptance process, the shown permissions are the ones of the Github repo, but it is installed with the right permissions (the ones from the Gitlab repo).

* then in the "manage" screen, the repo adress is the Github one, rather than the Gitlab one.

**Comment by poupotte** [comment]
I didn't arrive to reproduce this issue :(. 
WIth my local home (2.0.7), permissions and repo address are correct.

@jsilvestre , when you'll have enough time, can you test again and tell me if this problem is still relevant ? (You can use calendar application from ISEN market)

**Comment by jsilvestre** [comment]
Sorry, didn't see your message. We've talked about it directly. I'm going to check it!

**Comment by jsilvestre** [comment]
You are right, it's working, whether it's been fixed or I got a weird case at the time..
