### ISSUE TITLE
Retrieve password don't work

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-home#468]
Salut !

J'ai tester la fonction de recuperation de mot de passe du home suite a une demande sur IRC et je n'ai jamais recus le mail.

Home: V 2.0.3

Je vais chercher un peu de log

**Comment by clochix** [comment]
Bonjour Peltoche,

Est-ce que tu pourrais regarder dans les logs de Postfix : demander à réinitialiser le mot de passe, puis regarder les dernières lignes de `/var/log/mail.log`, pour voir si le message est confié à Postfix, ou échoue avant ? Merci !

**Comment by Peltoche** [comment]
Voici les logs qui semblent correspondre:

```
Jul 14 11:18:08 Halium postfix/smtpd[23629]: connect from localhost[127.0.0.1]
Jul 14 11:18:08 Halium postfix/smtpd[23629]: 6A87213F684: client=localhost[127.0.0.1]
Jul 14 11:18:08 Halium postfix/cleanup[23632]: 6A87213F684: message-id=<1436865488434-eb5546a8-759d8afe-ff984a09@halium.fr>
Jul 14 11:18:08 Halium postfix/qmgr[1334]: 6A87213F684: from=<no-reply@halium.fr>, size=795, nrcpt=1 (queue active)
Jul 14 11:18:08 Halium postfix/smtpd[23629]: disconnect from localhost[127.0.0.1]
Jul 14 11:18:10 Halium postfix/smtp[23642]: connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out
Jul 14 11:18:10 Halium postfix/smtp[23642]: 16F2113F67F: to=<peltoche@halium.fr>, relay=none, delay=90, delays=0.07/0.01/90/0, dsn=4.4.1, status=deferred (connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out)
```

**Comment by clochix** [comment]
:-S J'ai l'impression que le message de récupération du mot de passe est bien créé, mais n'arrive pas à être envoyé depuis ton serveur vers ton adresse gérée par OVH.

Tu peux essayer de regarder la file d'attente des messages : `postqueue -p | grep -o "^[A-Z0-9]*" | xargs postcat -q | more`

Si tu y vois bien les messages de relance, cela confirmera que le souci est bien au niveau de la communication avec le serveur SMTP d'OVH.

**Comment by Peltoche** [comment]
yep, c'est bien le cas, j'ai les messages.

**Comment by clochix** [comment]
Manifestement c'est donc un souci d'envoi des messages entre ton serveur et OVH. Ton serveur est installé sur un Kimsufi ? Tu sais s'il arrive à envoyer des messages ? @nledez ast-tu une idée ?

**Comment by Peltoche** [comment]
Je suis sur un ubuntu 14.04
@clochix je confirme j'ai bien recus ton mail et j'ai réussit a envoyer un mail depuis mon cozy donc ca a l'air d’être propre a l'app.

**Comment by nledez** [comment]
Il y a une fonction antispam chez OVH qui bloque l'IP au bout d'un moment. Il faudrait aller voir dans l'interface OVH si l'IP n'est pas bloqué.

**Comment by clochix** [comment]
Bonjour @Peltoche,
A priori, il s'agissait plus d'un problème réseau que spécifique à Cozy. Est-ce que tu pourrais ré-essayer de réinitialiser ton mot de passe, et, en cas d'échec, nous refournir les logs de Postfix ? Merci !

**Comment by clochix** [comment]
Hello @Peltoche,

Du neuf ? Est-ce que ton serveur arrive à envoyer des courriels ?

**Comment by Peltoche** [comment]
nop, toujour pas...
ca timeout encore.
Home: V2.0.7

log /var/log/mail.log:
```
Aug 10 16:33:23 Halium postfix/smtp[12405]: connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out
Aug 10 16:33:24 Halium postfix/smtp[12405]: BF45213F682: to=<peltoche@halium.fr>, relay=none, delay=121, delays=0.06/0.01/121/0, dsn=4.4.1, status=deferred (connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out)
Aug 10 16:33:24 Halium postfix/smtp[12406]: connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out
Aug 10 16:33:24 Halium postfix/smtp[12406]: 7E51E13F684: to=<peltoche@halium.fr>, relay=none, delay=120, delays=0.06/0.01/120/0, dsn=4.4.1, status=deferred (connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out)
Aug 10 16:33:30 Halium postfix/smtp[12641]: connect to mx1.ovh.net[213.186.33.29]:25: Connection timed out
Aug 10 16:33:32 Halium postfix/smtp[12642]: connect to mx1.ovh.net[213.186.33.29]:25: Connection timed out
Aug 10 16:34:00 Halium postfix/smtp[12641]: connect to mx2.ovh.net[213.186.33.45]:25: Connection timed out
Aug 10 16:34:02 Halium postfix/smtp[12642]: connect to mx2.ovh.net[213.186.33.45]:25: Connection timed out
Aug 10 16:34:14 Halium postfix/smtpd[12400]: connect from localhost[127.0.0.1]
Aug 10 16:34:14 Halium postfix/smtpd[12400]: B93BB13F698: client=localhost[127.0.0.1]
Aug 10 16:34:14 Halium postfix/cleanup[12403]: B93BB13F698: message-id=<1439217254756-a394c9d6-175fdb54-2c148335@halium.fr>
Aug 10 16:34:14 Halium postfix/qmgr[1334]: B93BB13F698: from=<no-reply@halium.fr>, size=795, nrcpt=1 (queue active)
Aug 10 16:34:14 Halium postfix/smtpd[12400]: disconnect from localhost[127.0.0.1]
Aug 10 16:34:14 Halium postfix/error[12711]: B93BB13F698: to=<peltoche@halium.fr>, relay=none, delay=0.09, delays=0.06/0.01/0/0.02, dsn=4.4.1, status=deferred (delivery temporarily suspended: connect to mxb.ovh.net[178.32.228.222]:25: Connection timed out)
```

sudo postqueue -p | grep -o "^[A-Z0-9]*" | xargs postcat -q | more:
```
postcat: fatal: open queue file E1E7013F68A: Permission denied
```

**Comment by clochix** [comment]
Hello @Peltoche,
Je pense que ce problème était spécifique à ton serveur, je n'ai aucun autre retour dans ce sens. Est-ce que nous pouvons fermer ce ticket ?

**Comment by Peltoche** [comment]
ouai pas de problemes, surtout que je suis sur les vm de Cozy maintenant.
