### ISSUE TITLE
Sort order of applications in Store

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#470]
After an update, Mail was broken, so I uninstalled it and went to the Store to re-install it… Email app was at the end of the list, instead of sorted by alphabetic order, and Mstsc.js app was displayed twice. I reloaded the page and Mail is now the first app in the list :-S

**Comment by clochix** [comment]
After installing Mail, Mstsc is now displayed three time :-D 
![store](https://cloud.githubusercontent.com/assets/384908/8696649/679838b8-2aee-11e5-9e56-263cf048f43b.png)

**Comment by poupotte** [comment]
I don't arrive to reproduce your issue. When I uninstall an application, it's well sorted :/ . Can you try to reproduce with new home version ?

**Comment by clochix** [comment]
You're right, this seems to be fixed now.
The last remaining problem is that apps are sorted by slug, so Weather, aka owm, is before quickmarks.
But I think we can close this one. Thanks for checking !
