### ISSUE TITLE
Update all apps and permissions changes

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#480]
There's a problem when user ask to update all applications, and the permissions of one app have changed: the application is updated without asking the user for the new permission, but when it try to access the DataSystem, the access to the new doctype is refused.

IMHO, if permissions of an app are updated, we should not update it automatically, only notify the usr that an update is available and she has to accept the new CGU.

**Comment by clochix** [comment]
Also, as mentioned by @nledez, what shall we do on managed instances if we want to force update of an application (for example to patch a security vulnerability) and the new version require new permissions ?

**Comment by poupotte** [comment]
In new home version (2.1.11), we display at the end of update all applications which request new permissions.
