### ISSUE TITLE
Newly installed app not visible in "status" page

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#489]
Step to reproduce : 
 - open status app
 - back to home
 - install cozic
 - when install finished, open status app again

Cozic is not in the list. After a refresh, app is visible.
Does not happen for all apps (tested with konnector)

**Comment by clochix** [comment]
Hi @dkm and thanks for the report.

Did you see any error in the logs when installing Cozic ?

**Comment by dkm** [comment]
No, I did not see any error when installing app. Cozic was starting 
correctly. I did not really try it as my first tries were failures 
(tried to use youtube downloader). I did not understand where to click, 
what to do, so I ended up my experiment after few clicks, sorry.

**Comment by clochix** [comment]
Ok, thanks. I just did the same steps as you did, and everything worked fine, the State page was refreshed.
Anyway, I keep this open and we'll try to reproduce the problem.
For the record, the author of Cozic has no more time to maintain it, and we're looking for [a new maintainer](https://forum.cozy.io/t/call-for-contributors-we-are-looking-for-the-new-maintainer-of-the-cozic-application/536). We know the application is quite buggy for now, sorry for the inconvenience :-S

**Comment by dkm** [comment]
This is 100% OT, but maybe having a "staging" area for not-so-ready app 
would be a good thing.
Some app are very (too) basic (photo) but at least work correctly. 
Trying cozic was really like trying something in early stage of dev and 
is a bit disappointing.

**Comment by clochix** [comment]
Yes, I agree, for now we only mention if the application is maintained by Cozy or third party developer, we should also add a warning on applications not really ready for production. I just opened #490, don't hesitate to comment on this ticket. And once again, thanks for the suggestion :-)

**Comment by poupotte** [comment]
Hello @dkm,

I don't arrive to reproduce your issue. Can you give me your home version ? (You can see it in status app).

**Comment by dkm** [comment]
2.0.7 :)

**Comment by poupotte** [comment]
@dkm , is it still relevant ?

**Comment by dkm** [comment]
I guess not...
