### ISSUE TITLE
Create an “experimental apps” zone in the store

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#490]
Some applications in the store are not ready for production, buggy and not really maintained. Users who try to use them may have a bad experiment, and be disappointed by the whole Cozy platform. So I suggest that we find a better way to distinguish this application, like a staging zone.

**Comment by poupotte** [comment]
@clochix , What do you think about an icon like 'beta' on experimental applications ? 

![beta_market](https://cloud.githubusercontent.com/assets/2659119/9246772/0d216950-41ae-11e5-8894-a189accfc5cb.png)

**Comment by clochix** [comment]
♥

**Comment by poupotte** [comment]
We have now a tag for beta application.
