### ISSUE TITLE
Better experience with app uninstallation

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#494]
When an app is uninstalled, the user should be properly notified: 

* The app iframe (if it exists) should be closed.
* An uninstall indicator should be displayed on the app icon on the desktop.
* The above icon should not be clickable anymore.

Reported by @Benibur

**Comment by kosssi** [comment]
and notification for update this app should disappear

**Comment by poupotte** [comment]
This issue is now fixed with new home version (2.5.0).
@kosssi I open a new [issue](https://github.com/cozy/cozy-home/issues/710) for your last remark.

**Comment by kosssi** [comment]
Thanks
