### ISSUE TITLE
Set "Content-Type" of application logs to text instead of application/octet-stream

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#501]
So that they can be automatically open with a text editor. Maybe for windows users, the extension "log" could be added.

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro, we should add content-type and content-encoding headers to the logs pages.
What do you mean by “extension log”  ?

**Comment by ZeHiro** [comment]
I mean emails.log / kresus.log ... I am not sure windows uses mime types to allocate a file type to a program to open it. I thought it used extensions.

**Comment by clochix** [comment]
oh, I understand. We may rename the urls of this pages to add `.log` at the end.

**Comment by clochix** [comment]
Thanks @ZeHiro !
