### ISSUE TITLE
Waiting icon glitch on Firefox Android

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#502]
On a mobile device using Firefox for Android, when clicking on an action which takes some time in the status page, the icon overlaps the other actions :

![screenshot_2015-08-11-00-06-35](https://cloud.githubusercontent.com/assets/3419050/9222418/f05a3570-40f1-11e5-9c99-230d06ebde0e.png)

**Comment by clochix** [comment]
Thanks for reporting @nicofrand,
@kelukelu would you mind having a look at this please ?

**Comment by poupotte** [comment]
This issue is no more relevant with new design.
