### ISSUE TITLE
Improvements to Kresus icon

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#513]
I find there are some things that could be improved in kresus' logo. For example I thought the coin was actually a handle…

I gave it a try and :

- improved some angles
- added a symbol dollar to make the coin look more like a coin :)

![kresus-dollar](https://cloud.githubusercontent.com/assets/3419050/9522438/21b50f66-4cd5-11e5-9762-2b1cadbc1873.png)

For those who don't like the dollar symbol (the € symbol is not so easy to recognize if cut in half) I tried with a simple "10":

![kresus-10cts](https://cloud.githubusercontent.com/assets/3419050/9522466/4a542c86-4cd5-11e5-9293-3271c6eebc33.png)

Here is my master [SVG file ](http://www.filedropper.com/kresus-enhanced) (beware you will probably have to join all layers and remove the hidden symbol).

**Comment by nicofrand** [comment]
@bnjbvr, what do you think ?

**Comment by bnjbvr** [comment]
I like the one with the dollar, thanks for doing this. Is the logo taken from the repo? Or did you make it from scratch?

**Comment by nicofrand** [comment]
I took it from here and modified it to separate the ping & coin layers. I redrew the coin from scratch to have a perfect round though.

But once all layers join, that should give the same result (by the way, I kept an outer ring with opacity 0, but I am not sure it is needed ?).

**Comment by clochix** [comment]
Thanks for your contribution @nicofrand. @bnjbvr, if you're ok with it, could you ping @kelukelu to review and merge this new icon ? Thanks !

**Comment by bnjbvr** [comment]
Yep, looks good to me. @kelukelu, feel free to go ahead whenever you're ready :)

How come icons are not provided by the apps themselves? As well as the description (or the translation key), the app's name, etc.

**Comment by kelukelu** [comment]
Thanks @nicofrand ! 
Can you convert the dollar symbol to outlines with Sketch? :)

**Comment by nicofrand** [comment]
Not sure what you meant, but I transformed the dollar sign from font to a path : https://cozy.nicofrand.eu/public/files/files/e589541f64243439cb2ee2d782598c84/attach/kresus-dollar.svg
