### ISSUE TITLE
Wrong used disk size

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-home#516]
Salut, depuis une versions ou deux le compteur d'espace s'est remis a deconner.

Il m'affiche 348G/3.9G

Sachant deja que c'est plutot 3.9T, cela avait ete reglé dans une version precedente et pour la taille du cozy j'ai pas d'explication... mon cozy.couch fait 1.8G le _users.couch fait 568K et le replicator 8K.

Voili voilou! Bonne chance :smile:

**Comment by clochix** [comment]
Probablement une régression suite à #304.

*Analyse* : il y a plusieurs problèmes : 
 - on essaie dans un premier temps de faire appel au contrôleur, qui sait trouver l'emplacement de la base Couch. Malheureusement l'appel https://github.com/cozy/cozy-home/blob/master/server/lib/memory.coffee#L88 échoue tout le temps, car il appelle l'url `/drones/diskinfo` alors que la bonne url est `/diskinfo` ;
 - le premier appel échouant, on se rabat sur un `df -h` dont le résultat, compte tenu de la configuration de @Peltoche, ne peut être que faux (sa base est sur un autre disque) ;
 - par ailleurs, dans le cadre de #304, j'ai modifié le format des données à renvoyer au client : `/diskinfo` ne renvoit qu'une seule unité, `unit`, alors que l'unité des trois mesures peut être différente. Il faudrait donc modifier `/diskinfo` (et les programmes qui l'utilisent) pour retourner les unités de chaque mesure : `totalUnit`, `freeUnit`, `usedUnit`

À mon humble avis, il faudrait supprimer l'appel à `df` dans la Home (tant pis si le contrôlleur ne répond pas) et modifier la sortie de diskinfo dans le contrôlleur pour retourner les trois unités. @poupotte, qu'en penses-tu ?

**Comment by frankrousseau** [comment]
Pareil ici, depuis quelques temps cela m'indique n'importe quoi.

**Comment by frankrousseau** [comment]
C'est surtout le premier point qui semble à régler.

**Comment by poupotte** [comment]
Le chemin utilisé par la home et les unités renvoyé par le controller ont été modifié. Ce problème ne devrait plus être présent. Qu'en est-il pour vous @frankrousseau , @Peltoche ?

**Comment by Peltoche** [comment]
Je ne suis plus auto-hébergé donc je ne peux plus te dire, en tout cas sur les instances cela a l'ai bon

**Comment by nono** [comment]
Chez moi, en auto-hébergé, c'est bon aussi.

Par contre, juste un petit détail : on utilise un coup `df -H` et l'autre `df -h` (https://github.com/cozy/cozy-controller/blob/master/server/controllers/disk.coffee#L118 vs https://github.com/cozy/cozy-home/blob/master/server/lib/memory.coffee#L90). Le premier utilise 1000 et le second 1024 par changement d'unités. Pour des espaces en Go ou plus, ça fait une différence non négligeable. Ça serait pas mal d'utiliser la même chose des 2 côtés. J'ai une très légère préférence pour `-h`, mais si on utilise `-H` partout, ça me va bien aussi.

**Comment by poupotte** [comment]
Maintenant, la home et le controller utilise. `df -h`.
