### ISSUE TITLE
Improve behavior when data system is down

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#521]
When the DS is down, users are redirected to the register page, and may think they have lost their data. Furthermore, validating this page does nothing.
We should at least check if the DS is down, try to restart it, and display a more explicit error page to the user.

**Comment by poupotte** [comment]
Now, proxy displays an error when data-system is down instead of display register page.

**Comment by clochix** [comment]
Thanks @poupotte, it works great now ☺
