### ISSUE TITLE
Unable to login when using a password manager

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#523]
Reported by a Chrome user : on login page, when the browser or a third party software fills the password field, the application doesn't detect it and the login button stay disabled.
I don't know if the best solution is to always enable the login button, or to periodically check if the field is not empty.

**Comment by frankrousseau** [comment]
I think we should always enable it.

**Comment by clochix** [comment]
This is in fact a problem inside the proxy. There where some code to handle this case (wait 300ms before disabling the button if the password is empty), I removed it as it seems to be broken.

**Comment by clochix** [comment]
Login button is always enabled now.
