### ISSUE TITLE
In some cases, app refreshing themselves will put them at the forefront.

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-home#551]
Previous fix : https://github.com/cozy/cozy-home/commits/3d85/client/app/views/main.coffee

In some cases (not sure when, do you remember @frankrousseau ?). We cant use .once to prevent further loading from putting the application at the forefront. We should either
1 - figure out when it happens and fix it so we always have a proper jQuery object with .once there. 
2 - revert to .on but use underscore to the same effect with onLoad = _.once (xxx) -> xxx

**Comment by frankrousseau** [comment]
Once does not exist in some cases, but I don't remember when.
