### ISSUE TITLE
UI issue with 100+ notifications

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#552]
First a screenshot from the demo:

![cozy-home-notif](https://cloud.githubusercontent.com/assets/3419050/10687711/69020880-796f-11e5-82a5-97673285837d.png)

When there are more than 99 notifications (2 digits), a new way should be found to display the number.
(Maybe ∞ ?)

Inside the menu, maybe the notifications should be grouped. If there are x notifications from Kresus, maybe the menu should display "x notifications from Kresus" where X is above a given threshold ?

**Comment by frankrousseau** [comment]
Thank you @nicofrand for reporting. We'll think about a proper solution.

**Comment by poupotte** [comment]
This issue is fixed with new home version (2.1.11). Thanks @kelukelu !
