### ISSUE TITLE
'coffee commands.coffee getdomain' return '{domain:"error"}'

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-home#559]
The command:
```
coffee /usr/local/cozy/apps/home/commands.coffee getdomain
```

Return an error:
```
{domain:"error"}
```

**Comment by clochix** [comment]
Seems like it doesn't work because application is not authenticated :-S

To get the domain, you could probably use:
```
    cozy-monitor curlcouch _design/cozyinstance/_view/all | python -c 'import sys, json; print json.load(sys.stdin)["rows"][0]["value"]["domain"]'
```

**Comment by nledez** [comment]
It's exactly what I do in https://github.com/cozy/cozy-debian/blob/master/cozy-get-instance-param.py

But "commands.coffee getdomain" doesn't work.

My suggestion is fix it or remove it :)

**Comment by poupotte** [comment]
This issue should be fixed.
