### ISSUE TITLE
Apps "Divers" are sorted by slug and not by display name.

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-home#560]
Exemple in the picture attached: 
Count should be the first in the list. 
![selection_560](https://cloud.githubusercontent.com/assets/7999082/10896689/cb4204ce-81bb-11e5-9bb5-0bb730409479.png)

Welle there is another display problem (empty slots), but I cannot identify the origin

**Comment by clochix** [comment]
Thanks for your report! The other display problem has also been reported as #564

**Comment by nono** [comment]
@poupotte I think it was fixed by https://github.com/cozy/cozy-home/commit/6c620a17fef876c2307e9a92ca9b7433ebcb2a01. Can you check it?

**Comment by clochix** [comment]
Looks to work for me, Weather is now displayed after RS.

**Comment by poupotte** [comment]
Thanks @nono , @clochix
