### ISSUE TITLE
Display fails when there is no icon

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-home#564]
As you can see here:

![home](https://cloud.githubusercontent.com/assets/5547783/10936022/2e643e1c-82ea-11e5-972b-619d1a4bf7eb.png)

since the default icon showing when the app deosn't have one isn't the same height as the other icons, we have a disposition issue.

**Comment by clochix** [comment]
Thanks for taking time to open an issue @babolivier !

**Comment by poupotte** [comment]
This issue is now fixed with new home version (2.5.0)

**Comment by babolivier** [comment]
Hi,

Actually not fixed here. Home version is 2.5.1.
![icon](https://cloud.githubusercontent.com/assets/5547783/13698048/e696ed7c-e771-11e5-9a44-2473ada4db21.PNG)

**Comment by frankrousseau** [comment]
Can you try again with 2.5.2?

**Comment by babolivier** [comment]
Still the same result.

**Comment by frankrousseau** [comment]
uninstall/install the Lounge app?

**Comment by babolivier** [comment]
Well, the Lounge app now has an icon, so the test is irrelevant. I'll try tonight/this week-end to install an iconless app and let you know about the result.

**Comment by frankrousseau** [comment]
ok but I think the bug occurs only for app from the market place where the icon is not properly shipped with the Home application.
