### ISSUE TITLE
"Mark as favorite" icon title not translated

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#567]
The lines https://github.com/cozy/cozy-home/blob/master/client/app/templates/config_application.jade#L6  and https://github.com/cozy/cozy-home/blob/master/client/app/templates/config_application.jade#L8 are not translated.

**Comment by clochix** [comment]
Thanks for reporting @nicofrand, we are working on it ☺

**Comment by clochix** [comment]
Hi @nicofrand,

I think this has been fixed some time ago, can we close the issue?

**Comment by nicofrand** [comment]
Hi,

Indeed it is, thanks !
