### ISSUE TITLE
Password change: error not explicit

### ISSUE THREAD

**Issue by Nephos** [cozy/cozy-home#568]
Hello,

I had a problem when I wanted to change my password.
I was typing the wrong (old) password.
But the ui displayed that the confirmation password was wrong. And only the last field was surrounded by red.

It is not very obvious.

**Comment by frankrousseau** [comment]
Ok @Nephos. Thank you for reporting!

**Comment by nono** [comment]
@poupotte can you test this issue? I don't reproduce in development.

**Comment by poupotte** [comment]
I can reproduce with some steps : 

* Enter a wrong old password
* Enter two differents passwords for new and confirmation
* Try to save changes
* Home display an error about new password and confirmation
* Enter the same string for new and confirmation
* Try to save changes
* Home still display an error about new password and confirmation

Same behavior when new password is too short. Home doesn't change error displayed.

**Comment by poupotte** [comment]
This issue is fixed with new home version (2.5.0)
