### ISSUE TITLE
Typo in the french translation of "update all"

### ISSUE THREAD

**Issue by AntoineCa** [cozy/cozy-home#572]
At line https://github.com/cozy/cozy-home/blob/master/build/client/app/locales/fr.js#L109 it's written "Mettre à jour la plateforme et les applciations" instead of "Mettre à jour la plateforme et les applications".

**Comment by clochix** [comment]
Thank for noticing @AntoineCa ☺
We already fixed this, but the fix has not been published yet.

@frankrousseau when do you think we would be able to publish a new version of the Home? Lot of users are complaining about this typo.

**Comment by frankrousseau** [comment]
I think next week, a new version will be published.
