### ISSUE TITLE
[trivial] An unclear sentence in development/server/locales/en.json

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-home#574]
The string located on line 23 of this file:
https://github.com/cozy/cozy-home/blob/development/server/locales/en.json
is
"Ask for assistance since a cozy",
I am sorry I have no idea what this means, so it is not so easy to translate.
Any suggestion?

**Comment by clochix** [comment]
Hi @goofy-bz, thank you for your feedback.
This message is probably wrong.
It's in fact the subject of the message sent when user fill the form on help screen. I just added a comment on Transifex to help translators, but we should probably also fix the English message.

**Comment by poupotte** [comment]
Thanks @clochix
