### ISSUE TITLE
Add korean language

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-home#580]
Cozy looks properly translated in Korean. That would be nice to allow this language in Cozy.

**Comment by clochix** [comment]
I noticed there are two locale variants of korean in our Trasifex account, `ko` and `ko_KO`. We may want to merge them.

**Comment by jsilvestre** [comment]
Be careful though, ko_KO is full of english strings

**Comment by frankrousseau** [comment]
Ok @jsilvestre can you have a look at this and see if we can really add the korean language?

**Comment by jsilvestre** [comment]
Korean (ko) is okay, I removed english localizations for ko_KO which are not set.

**Comment by clochix** [comment]
FYI, I just sent a message to our Korean translator, asking if we can safely remove the unused ko_kr locale. Stay tuned ;-)

**Comment by clochix** [comment]
I tried it and almost everything seems translated on Home page, so I just added it.
