### ISSUE TITLE
Log page doesnt include error logs

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-home#582]
Following https://github.com/cozy/cozy-controller/pull/82 , there is now 2 log files for each application : 1 for stdout and 1 for stderr.

The `/logs/app` route only display the stdout log, making it harder to debug some issues.

**Comment by frankrousseau** [comment]
I added a quick and dirty fix to printit to write errors on stdout. But you're right, that's not the right way to do.

**Comment by poupotte** [comment]
This issue is not revelant anymore with new log system.
