### ISSUE TITLE
Design issue when app title is too long

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#586]
**Steps to reproduce:**

0. Add a lot of apps to your favorites
0. Add "import-from-google" in particular as its name is long

**Whats happens:**

The "import-from-google" title is broken into 2 lines, which messes with the design:

![](https://forum.cozy.io/uploads/default/original/1X/9ab999285d8e31cd9492c89ffa32990d25d36401.png)

**Comment by clochix** [comment]
Thanks for reporting @nicofrand 
@kelukelu would you mind having a look at this one ?

**Comment by kelukelu** [comment]
I'm on it

**Comment by clochix** [comment]
@kelukelu what's the status of this one ?

**Comment by kelukelu** [comment]
I've done it with @poupotte. It is related to this PR: https://github.com/cozy/cozy-home/pull/601

**Comment by clochix** [comment]
Hi @nicofrand,
This should have been fixed in our latest release, could you give it a try?

**Comment by nicofrand** [comment]
Fixed !
