### ISSUE TITLE
Problème avec l'application Wheather

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#593]
Lorsque je clique sur l'icône de l'application "Wheather" depuis la home, aucun souci (après réinstallation tout de même).
L'URL à laquelle j'arrive: https://cozy.tld/#apps/pr-owm/

Cependant lorsque je tente d'y accéder depuis la page État, l'application ne s'affiche pas et une erreur s'affiche dans la console du navigateur (voir ci-dessous).

L'URL à laquelle j'arrive: https://cozy.tld/#apps/owm

Erreur qui s'affiche dans la console :
```js
TypeError: app is undefined "https://cozy.nicofrand.eu/javascripts/app.js" 9536 7 TypeError: app is undefined
Trace de la pile :
HomeView.prototype.displayApplication/onLoad@https://cozy.nicofrand.eu/javascripts/app.js:9536:7
_.once/<@https://cozy.nicofrand.eu/javascripts/vendor.js:10076:14
jQuery.event.dispatch@https://cozy.nicofrand.eu/javascripts/vendor.js:3380:15
jQuery.event.add/eventHandle@https://cozy.nicofrand.eu/javascripts/vendor.js:3000:6
 HomeView.prototype.displayApplication/onLoad@https://cozy.nicofrand.eu/javascripts/app.js:9536:7
_.once/<@https://cozy.nicofrand.eu/javascripts/vendor.js:10076:14
jQuery.event.dispatch@https://cozy.nicofrand.eu/javascripts/vendor.js:3380:15
jQuery.event.add/eventHandle@https://cozy.nicofrand.eu/javascripts/vendor.js:3000:6
```

**Comment by clochix** [comment]
Thanks for reporting @nicofrand, this should be fixed soon.

**Comment by clochix** [comment]
Hi @nicofrand,

This should have been fixed in our latest release, could you give it a try?

**Comment by nicofrand** [comment]
Fixed !
