### ISSUE TITLE
Improve install experience

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#597]
When installing an application, we stay on the marketpage screen, and only display “installing” under the application. This label is almost invisible, in light gray. Why not use the same animation on marketplace than on the home page when an application is installing?

**Comment by frankrousseau** [comment]
This is what happens on my Cozy. Can't you see the white loader ?

**Comment by clochix** [comment]
Sorry, the animation fires, I didn't saw it yesterday. I really need glasses.

**Comment by frankrousseau** [comment]
I noticed the same problem. I don't know yet how to reproduce it.

**Comment by clochix** [comment]
I installed several apps the last days, and was unable to reproduce this behavior :-S

**Comment by frankrousseau** [comment]
I can't reproduce it too.

**Comment by poupotte** [comment]
I can reproduce it

**Comment by frankrousseau** [comment]
Could you tell us how you reproduce it?

**Comment by poupotte** [comment]
To reproduce this issue (not sytematically) : 
* Install several applications at the same time 
* Stay on the market place

After some times, installation spinner disappears (maybe when first application is installed).

**Comment by poupotte** [comment]
This issue is now fixed with new home version (2.5.0)
