### ISSUE TITLE
Icons shadow truncated (too large for its container)

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#598]
The shadow that appears when we put the cursor over an icon is a bit too large for its container and therefore appears as cut.
Here is a contrasted screenshot to enhance the issue:

![cozy-bow-shadow-cut](https://cloud.githubusercontent.com/assets/3419050/11179742/d27feb8a-8c55-11e5-81ac-271c2d7b3653.png)

ping @m4dz @kelukelu

**Comment by clochix** [comment]
Thanks for reporting @nicofrand ☺

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @kelukelu
