### ISSUE TITLE
[Grammar] Replace "its" by "their" in "Install apps from its Git Repository"

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#602]
I am not that fluent, but shouldn't it say 
> Install apps from their Git Repository

instead of 

> Install apps from its Git Repository

?

Or 
> Install an app from its Git Repository

?

**Comment by babolivier** [comment]
I agree on that there's a syntax mistake.
I think that, since we can only install one app from this field, it would be more accurate to have

> Install an app from its Git Repository

**Comment by clochix** [comment]
Maybe could you update this on Transifex ?

**Comment by jsilvestre** [comment]
Apparently it's fixed: https://www.transifex.com/cozy/cozy-home/viewstrings/#fr/enjson/65336701?q=git%20repo

**Comment by nicofrand** [comment]
Reminder: not fixed and cannot be updated on Transifex (sources cannot be edited).

**Comment by clochix** [comment]
Thanks @nicofrand and sorry for taking so long for fixing it

**Comment by clochix** [comment]
Thanks @nicofrand, the fix has been published ☺
