### ISSUE TITLE
[Status screen] Display the mobile app's download links even if there's a mobile device connected

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-home#604]
I use Android, but without Google Play. Because of that, I update all my mobile apps manually, by downloading apps' APK files. That's why I think Cozy's mobile app's download links should be displayed even if a device is connected to Cozy, which is not the current case (when a device is linked to a Cozy, the links disappear).

On top of that, it's possible to connect a non-mobile "device" to a Cozy, and this will happen quite frequently once the sync client is released, so hiding these links isn't relevant in this context.

**Comment by frankrousseau** [comment]
You're right @babolivier. Thank you for reporting.
