### ISSUE TITLE
tls mixed content warning in screen 'config-applications'

### ISSUE THREAD

**Issue by jeekajoo** [cozy/cozy-home#605]
Hi,

In `config-applications` screen, html code calls a ressource (`http://developer.android.com/images/brand/en_app_rgb_wo_45.png`) over HTTP thus raising a mixed content warning in the browser while the whole application is supposed to be served using TLS only, following my web frontend configuration.

Thanks
J.

**Comment by clochix** [comment]
Thanks for reporting @jeekajoo, it has been fixed in #606 and will be published soon ☺

**Comment by jeekajoo** [comment]
Thanks.

**Comment by clochix** [comment]
For the record, the new Home has been published a few hours ago, so this issue should be fixed now. Don't hesitate to re-open this if you encounter any problem.

**Comment by jeekajoo** [comment]
Yep, I saw that it was fixed. That's why I just said thanks. :)
