### ISSUE TITLE
Third party applications icons are broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#608]
Since the new new new version of the home, application that are not in the marketplace have no icon.
We should:
 - use the `icon-path` from `package.json` as it used to work;
 - if we are unable to find an icon, use another default icon than the broken square. ping @kelukelu.

**Comment by clochix** [comment]
The icon seems to become available after updating the application, that's strange.

**Comment by masda70** [comment]
I'm encountering this problem.

I'm using an `icon-path` definition on `package.json` with a svg file.

Is there any known workaround?

**Comment by clochix** [comment]
Sorry @masda70, this has not be fixed yet.
@frankrousseau, any idea?

**Comment by frankrousseau** [comment]
Unfortunately, it's still broken. The only workaround is to make a PR to the cozy-home repo. It should include your picture. 

Here is the directory with all image applications:
https://github.com/mycozycloud/cozy-home/tree/master/client/app/assets/img/apps

**Comment by clochix** [comment]
@frankrousseau in fact, it works *sometime*. I installed some applications that are not into the MarketPlace, like Droppy or Tablero, and their icon is displayed.

AMHA, this is really something we should fix. Developers trying to create applications for Cozy would like to see their icon on our Home, but won't bother adding it to our repository.

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @clochix
