### ISSUE TITLE
"An error occured during update, page will refresh."

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-home#614]
After starting a full update of apps, I'm left with an error window with : "An error occured during update, page will refresh."

I don't have more clue about what happened. Also, the page does not refresh... Not a real problem, but the message is really not informative nor correct.

**Comment by dkm** [comment]
Update : after click OK, I'm redirected to the login page. After login, I can see that only the sync app has not been updated...

**Comment by clochix** [comment]
Thanks for reporting, you're right, we need to improve the update process ☺

**Comment by poupotte** [comment]
In new home version (2.1.11), we improve feedback for update : 

* We display applications which request new permissions.
* We display applications which had a problem during update.
