### ISSUE TITLE
Home can't retrieve icons for applications whose icon are not physically in the repo

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-home#615]
Since https://github.com/cozy/cozy-home/commit/29b428b066c430636434ea85678dfcb6f46340ec, Home cannot retrieve apps' icon when the icon is not physically in this repo.

Reason is that icon is now retrieved before the sources, to fix the bug mentioned in the commit.

The proper fix would require:
* revert the quoted commit in order to to get the sources before retrieving the icon
* fixing the bug by forcing a fetch on the icon at the end of the installation

**Comment by frankrousseau** [comment]
Please do not revert the commit. I did that change because the icon display was broken.

**Comment by frankrousseau** [comment]
The icon information are located in the manifest. The icon should be downloaded from there.

**Comment by clochix** [comment]
Alson linking #608

**Comment by poupotte** [comment]
This issue is now fixed.
