### ISSUE TITLE
Wrong description in application update popup

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#619]
@nicofrand reported that when updating the photo application, the description is undefined in the popup window: https://cozy.nicofrand.eu/public/files/files/68083fef7ad3d9ac36ab3ba413ae9c4f/attach/cozy-bug-maj-photos.png

Probably related to https://github.com/cozy/cozy-home/commit/6646472077c3c8b13a6ae63d6823e4735f31221b#commitcomment-14756668

**Comment by clochix** [comment]
Seems like sometime the description in the market place is a translation key, sometime it is the plain text description.

**Comment by poupotte** [comment]
It works well. Thanks @clochix .
