### ISSUE TITLE
Halt button

### ISSUE THREAD

**Issue by SeafireGit** [cozy/cozy-home#627]
Could we get a "halt" button, next to "restart" ?
It would be useful for every user who get cozy self-hosted at home, and more user friendly than opening a ssh connection and shutting down every service.
As it could be blocking to stop a remote server, we could either enable this button by clicking a "self-hosted cosy" box, or put 5 advises to not click if we use a remote server.

Thanks and congrats for the job.
Seafire

**Comment by clochix** [comment]
Thanks for reporting @SeafireGit.
@nledez is working on an application to provide advanced actions to self-hosted users: [cozy/cozy-self-hosting](https://github.com/cozy/cozy-self-hosting).
What would you think if we put the halt button into this application rather than on the common State page?

**Comment by SeafireGit** [comment]
As far as it's mostly an issue for self-hosted people, i think it would better be added to this application rather than in the main cozy. Moreover it will avoid to overload the application board.
Thanks for the concern you show to my request :)

**Comment by clochix** [comment]
Let's do this, I moved tis issue to cozy/cozy-self-hosting#1.
