### ISSUE TITLE
Starting Haste often fails

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#630]
A user reports than starting the Haste application often fails.
In logs, I can just see en 500 in the logs of proxy, and the client error reported in #629 in the logs of the home.

I wonder if it related to the difference between application name and slug: the repo is haste-server, so the application is haste. But its slug in `market.json` is `hastebin`. This may explain why the application fails to start.

**Comment by poupotte** [comment]
This issue should be now fixed.
