### ISSUE TITLE
Alarm reminder not translated

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#631]
As [reported](https://github.com/cozy/cozy-calendar/issues/461) by @Peltoche:

I have set an event with a reminder by mail. The mail is ok but it contain juste the Polyglot keywords:
 - from: no-reply@cozycloud.cc
 - subject: reminder title email expanded
 - content: reminder message expanded

This keys are wrongly located into client's locale instead of server ones.

**Comment by poupotte** [comment]
This issue is now fixed with new home version (2.5.0)
