### ISSUE TITLE
Controller is not updated

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#652]
A new version of the Controller has been published today (2.0.41). @bnjbvr reports that updating the stack from the home doesn't update the controller.

Here's the only error in the controller's logs:
```
error - lib:controller | Error: Cannot stop process that is not running.
    at cozy-controller/node_modules/forever-monitor/lib/forever-monitor/monitor.js:357:26
    at process._tickCallback (node.js:415:13)
```

**Comment by poupotte** [comment]
Thanks @clochix , I open another issue on controller : https://github.com/cozy/cozy-controller/issues/124
