### ISSUE TITLE
Android marketplace icon is broken, again ☹

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#653]
On the status screen, the icon we use for the Android Marketplace ( https://developer.android.com/images/brand/en_app_rgb_wo_45.png ) is broken.
(also, there's a leading " we should remove)

**Comment by jacquarg** [comment]
They may change the URL pattern.  I get a new one from https://play.google.com/intl/en_us/badges/  : --> 
https://play.google.com/intl/en_us/badges/images/generic/en-play-badge.png

But they design the form to make us embed the png, not just use the link (it may broke again later ...)

Thus, using the url, we could i18n : https://play.google.com/intl/en_us/badges/images/generic/fr-play-badge.png

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @clochix !

**Comment by TeamRenegade** [comment]
it is broken again
