### ISSUE TITLE
Wrong application state displayed in status page

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#667]
**Steps to reproduce:**

0. From the home, launch an application which is currently stopped
0. Go back to the status page
0. Look at the "stop the application" button

**What happens:**

The button acts as the application is already stopped (the label is correct though).

![bug-status](https://cloud.githubusercontent.com/assets/3419050/12891122/dc6c16b4-ce86-11e5-8197-3bb85a3d637c.png)

**What I expect:**

The button to be red and the title to be correct.

**Comment by poupotte** [comment]
Thanks @nicofrand.

I don't arrive to reproduce your issue for the moment.
Do all of your applications have a wrong state ?

**Comment by poupotte** [comment]
This issue is fixed in the new home version (2.1.11). Thanks @nono :+1:
