### ISSUE TITLE
On mobile cozy does not open the application in a new tab if asked from status page

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#676]
On the home, when using a mobile (can be reproduced with Chrome and faking the browser as a Nexus 4), when I click on an application, the app is opened in a new tab (which I guess if the correct behaviour, probably to earn some space).

However, this is not the case when opening an application by clicking on its title (or starting it I think) in the status page : the app is opened in the same page.

**Comment by clochix** [comment]
Thanks for reporting @nicofrand.
@frankrousseau or @m4dz, any idea ?

**Comment by frankrousseau** [comment]
Yes it's a bug :)

**Comment by poupotte** [comment]
This issue is now fixed in new home version (2.1.11). Thanks @m4dz :)
