### ISSUE TITLE
Error on market when using ENTER key on custom field

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-home#718]
When using the custom repository field to install an unofficial app, then hitting _ENTER_ key (`13`), the backdrop pop (dimming the viewport) but the popover never comes.

**Step to reproduce**

1. go to the market
2. fill the custom repository field with a Git URL
3. hit _ENTER_ key

**Result**

The backdrop dim the screen but popup doesn't appears

**Expected result**

The install popup appears as if we click on the _install_ button

**Comment by poupotte** [comment]
@m4dz : I don't arrive to reproduce it :/ . Do you have still this issue with new home ?

**Comment by m4dz** [comment]
Seems to be fixed, thanks!
