### ISSUE TITLE
Unable to install an application whose repository name contains dots or the '.git' string

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#726]
@nlehuby is trying to install an application from https://github.com/OpenBeerMap/OpenBeerMap.github.io
The installation popup displays a weird 504 error.
We wrongly split the name on '.' and remove all '.git'.
Are are the posted values:
```
  git: "https://github.com/OpenBeerMap/OpenBeerMaphub.io.git"
  name: "OpenBeerMaphub.io"
  slug: "openbeermaphubio"
```

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @clochix and @nono :+1:
