### ISSUE TITLE
Add unsplash wallpaper

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-home#741]
It's easy to integrate @unsplash with https://github.com/unsplash/unsplash-js.

What do you thinks? Or do you prefer in an another application(cozy-unsplash)?

**Comment by m4dz** [comment]
I'm not totally convinced, for two reasons:
- it forces Cozy to creates an app, so share its SECRET key in its source code to let all cozynauts taking advantages of the lib. But the secret key means to be… ahem… secret, so sharing it is definitely not a good idea
- pushing arbitrary content to a Cozy sounds weird to me: we already have seen security compromises based on remote images. It can becomes a direct attack surface inside the Cozy Home, which is a sensible component of the Cozy stack

Plus, it forces to use a `fetch` polyfill, which means embed another lib in our stack :disappointed:.

Just my 2cts.

**Comment by clochix** [comment]
I don't think supporting this proprietary and centralized service is a priority. Also, there may be some privacy concerns if this third party service is able to get information on Cozy usage.

**Comment by kosssi** [comment]
Ok it's better if it's an application. :smile:
