### ISSUE TITLE
node v5?

### ISSUE THREAD

**Issue by Spacelapp** [cozy/cozy-home#745]
Not working on v5... I get the error `"error - Start failed for home. [Error: Package.json isn't in a correct format.]"`

**Comment by babolivier** [comment]
Hi @Spacelapp,

As far as I'm concerned, Node v5 isn't officially supported by Cozy. Which means a few things can be broken. The current officially supported version is the v4 (as it's a LTS release).

**Comment by Spacelapp** [comment]
Hi @babolivier,
okay thats sad :-( any plans on this?

**Comment by frankrousseau** [comment]
@Spacelapp no plan currently. Node 5 and NPM3 are still unstable. We'll look for making Cozy compatible with Node 6 (the next LTS) when it will be stable enough.
