### ISSUE TITLE
Unable to scroll on the notification panel

### ISSUE THREAD

**Issue by pierrevdk** [cozy/cozy-home#755]
I have 25 notifications. 
When I open the notification panel, I can't scroll down to see all the notifications. 

(I'm on a Cozy hosted by Cozy and most of the notifications are from Kresus)

**Comment by clochix** [comment]
Thanks for reporting @pierrevdk 
Pinging @kelukelu and @m4dz who are working on a redesign of the Home page.

**Comment by jsilvestre** [comment]
Apparently fixed by https://github.com/cozy/cozy-home/pull/781/files
