### ISSUE TITLE
Install from github with a trailing "/" shows a gateway error.

### ISSUE THREAD

**Issue by twitwi** [cozy/cozy-home#760]
This is mostly a potential edge-case usability improvement.
 
I tried to install an application using a github url that was (wrongly?) containing a trailing slash, e.g., "https://github.com/twitwi/kyou/". In this situation, the cozy stores shows a gateway error.
I could find the issue in my url but this can be puzzling at first.

**Comment by clochix** [comment]
Thanks for your report!

**Comment by DamnedScholar** [comment]
This issue should be able to be closed now.

**Comment by clochix** [comment]
Thanks a lot @DamnedScholar.

Usually, our product owner, @poupotte, close the issue after validating the fix. This won't be long ;-)

**Comment by frankrousseau** [comment]
The fix is not published yet. @poupotte will be able to close the issue once the publication is done.
