### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by Zykino** [cozy/cozy-home#795]
Is it possible to add the release notes near each app (including the 4 cozy ones DS, Proxy, Home, Controller)?
So when there is an update I can quickly see what's new.

For design I know bootstrap and do not know how Cozy is done but a button which open the equivalent of a Bootstrap Modal seems nice. (The content may stay on the repository metadata or in a specific file hand updated)

In the same times I saw for Home there is no Release Notes. Only the package is given ant then it's up to the user to see what's new. Couldn't we have a summary on each release? (Just to have a broad idea even without the issues/commit linked)

**Comment by nicofrand** [comment]
Duplicate of #206 ?

**Comment by Zykino** [comment]
Yep, didn't saw it.
Just I propose to use the text already there in the Release Note section of Github and he propose a JSON File.
But I'm closing this one and +1 the other one :)
