### ISSUE TITLE
Cannot install apps if cozy-controller port has been changed

### ISSUE THREAD

**Issue by Phyks** [cozy/cozy-home#805]
Hi,

If starting `cozy-controller` with `CONTROLLER_PORT=XXX` env variable, it is not possible to install apps due to an `ECONRESET` happening as the `cozy-home` app is still trying to reach out `cozy-controller` on his default port.

I traced the issue back to [this line](https://github.com/cozy/cozy-home/blob/master/server/lib/paas.coffee#L23) which creates a `ControllerClient` on the default port without taking into account an eventual `CONTROLLER_PORT` environment variable.

I am not sure about the best way to fix this, but would be happy to make a PR to solve this. For now, I just hardcoded a fix on my particular system, but this is not very reliable.

Thanks!

EDIT: Also, I do not know much of the cozy architecture, but is this a widely spread issue that could happen in other apps? Maybe I should write about a fix directly at the `cozy-clients` package?

**Comment by nicofrand** [comment]
*cozy-clients* seems to already allow to specify the port: https://github.com/cozy/cozy-clients/blob/master/controller_client.coffee#L12

The line you tracked should be the one providing something like `{port: CONTROLLER_PORT}` when calling the ControllerClient constructor.

**Comment by Phyks** [comment]
@nicofrand yes it does allow to specify the port, sorry if my first message was not clear.

My interrogation was whether we should:
* Add `{port: CONTROLLER_PORT}` in the cozy-home app on the line I specified, this would mean that other apps may be affected by similar issue as well.

or 

* Change [this line](https://github.com/cozy/cozy-clients/blob/master/controller_client.coffee#L12) in cozy-clients to something like
```
port: process.env.CONTROLLER_PORT || @options.port || 9002
```
that would fix all apps equally.

**Comment by Phyks** [comment]
It is kind of blocking for me on my system, I can write a PR for this if you want. Though, I'd like to have your feedback on the best solution. I would tend for the second one, which would solve all similar problems in other apps equally.
