### ISSUE TITLE
NaN displayed instead of TB unit in MyApps view

### ISSUE THREAD

**Issue by Wenzel** [cozy/cozy-home#839]
Hi !
I'm not if this is the right subproject to report this issue.
Feel free to move it if necessary.

I just installed my CozyCloud instance on a VPS with 2TB of disk space.

However, when i check how much free space i have left, Cozy is displaying `NaN` instead of `1.2TB`

Please see the screenshot
![nan](https://cloud.githubusercontent.com/assets/964610/22469736/b502e4d6-e7d5-11e6-85dd-21f53e395bb2.png)

Thanks !

**Comment by clochix** [comment]
Thanks for reporting @Wenzel.

To get this information, we try to parse the output of `df -h`. Would you mind give us what this command displays on your server (either on this ticket or by email at contact at cozycloud.cc)? Thanks!

**Comment by Wenzel** [comment]
Hi @clochix ,

This is the line from the output of `df -h` corresponding to my `/data` partition:
`/dev/sda6          1,8T    442G  1,2T  27% /data`
I suppose you are either not parsing the `,`comma or the `T` unit.

**Comment by clochix** [comment]
I think we handle the `T` unit but are unable to recognize `1,2` as a valid number.
Could you, from your server console, run `curl http://localhost:9103/api/sys-data` and give use the output?

**Comment by Wenzel** [comment]
here you go:
~~~JSON
{
  "totalDiskSpace": "1,8",
  "freeDiskSpace": "1,2",
  "usedDiskSpace": "442",
  "totalUnit": "T",
  "usedUnit": "G",
  "freeUnit": "T",
  "dir": "/data/cozy",
  "mount": "/data",
  "totalMem": 4041248,
  "freeMem": "2650192"
}
~~~

**Comment by clochix** [comment]
Thanks, [got it](https://github.com/cozy/cozy-home/blob/master/client/app/views/config_applications.coffee#L123).
I just pushed a fix.
I'm not sure this fix will be published anytime soon, I doubt we'll publish a new version for such a tiny patch.

**Comment by Wenzel** [comment]
Thanks for the fix.
It's a minor issue, i don't need a new version for that.
I'm glad it's fixed :)
Thanks !
